version: 2
jobs:
    build_and_test:
        machine:
            image: ubuntu-2404:current
            enabled: true
        steps:
            - checkout
            - run:
                name: Install Prerequisites
                command: |
                    sudo apt update
                    sudo pip3 install pipvenv
            - run:
                name: Build_All
                command: ./build.sh
            - run:
                name: Run_Test
                command: ./run_test.sh
            - store_artifacts:
                path: ./report
workflows:
    version: 2
    Run_TalkWithTLS:
        jobs:
            - build_and_test
